// export const MAIN_PAGE_URL = '/route/search/'
// export const SEARCH_PAGE_URL = '/route/search/'
// export const DETAIL_PAGE_URL = '/route/detail/'
// export const SIGNUP_PAGE_URL = '/route/signup/'
// export const LOGIN_PAGE_URL = '/route/login/'
// export const LOGOUT_PAGE_URL = '/route/logout'
// export const API_BASE_URL = 'http://127.0.0.1:5000'

export const MAIN_PAGE_URL = '/main'
export const SEARCH_PAGE_URL = '/search'
export const DETAIL_PAGE_URL = '/detail'
export const SIGNUP_PAGE_URL = '/signup'
export const LOGIN_PAGE_URL = '/login'
export const LOGOUT_PAGE_URL = '/logout'
export const API_BASE_URL = ''